# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMobileCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter
  pod 'MobileCenter/Crashes', '~> 0.14.1'
  pod 'MobileCenter/Analytics', '~> 0.14.1'
  pod 'RNMobileCenterShared', '~> 0.11.2'

  

  target 'TestMobileCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestMobileCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter-tvOS

  target 'TestMobileCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
